services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    build:
      envVars:
        - key: NODE_VERSION
          value: 18
